### ISSUE TITLE
Unable to setup local environment 

### ISSUE THREAD

**Issue by kevingimbel** [lucapette/deloominator#97]
I followed the steps in https://github.com/lucapette/deloominator/blob/master/docs/developers-manual.md

1. I cloned the code to my machine in `$GOPATH/src/github.com/lucapette/deloominator`
2. I ran `make setup`
3. I ran `make` to build the server and UI. 

The problem is that the NodeJS dependencies are not installed by "make setup". 

```sh
$ make
cd ui && npm run build

> deloominator-UI@0.0.1 build /Users/kevingimbel/Development/go/src/github.com/lucapette/deloominator/ui
> webpack --progress -p --config webpack.production.js

module.js:529
    throw err;
    ^

Error: Cannot find module 'webpack-merge'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/kevingimbel/Development/go/src/github.com/lucapette/deloominator/ui/webpack.production.js:1:77)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deloominator-UI@0.0.1 build: `webpack --progress -p --config webpack.production.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deloominator-UI@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kevingimbel/.npm/_logs/2018-01-24T08_47_53_891Z-debug.log
make: *** [build-ui] Error 1
```

This can be fixed by either having another make target or adding the following to "make setup".

```
setup: 
  cd ui && npm install 
```

---

Should we add this to the `setup` target?

**Comment by lucapette** [comment]
closed by #99 

Thank you for reporting! Very helpful!
